version: '3'

services:
  camforchat-app:
    build:
      context: ./../build/ci
    env_file:
      - ./../configs/.env.test
    volumes:
      - ./..:/app
      - ~/go/pkg:/go/pkg
    depends_on:
      - camforchat-db

  # Database
  camforchat-db:
    image: postgres:alpine
    env_file:
      - ./../configs/.env.test
    expose:
      - "5432"

  camforchat-sqitch:
    image: isqad88/sqitch:0.2.0
    env_file:
      - ./../configs/.env.test
    volumes:
      - ./../db/src:/src
      - ./../scripts:/scripts:ro
    depends_on:
      - camforchat-db
