.PHONY: all clean test lint prepare race msan

all: test

test: prepare
	scripts/test/test.sh

lint: clean
	scripts/test/lint.sh

race: prepare
	scripts/test/race.sh

msan: prepare
	scripts/test/msan.sh

prepare: clean
	scripts/test/prepare.sh

clean:
	scripts/test/cleanup.sh

sh:
	scripts/test/sh.sh
